- name: Import Grafana GPG signing key
  apt_key: url=https://packages.grafana.com/gpg.key state=present
  become: yes

- name: Run lsb_release and register its output as a variable
  command: "lsb_release -cs"
  register: release_name

- name: Add Grafana repository
  apt_repository: 
    repo: "deb https://packages.grafana.com/oss/deb stable main"
    state: present
  become: yes

- name: Install Grafana packages
  apt: name=grafana state=present
  become: yes

- name: Start the Grafana service
  service: name=grafana-server state=restarted
  become: yes


