- name: ensure group "fileShareGroup" exists
  group:
    name: fileShareGroup
    gid: 1004
    state: present
  become: yes

- name: add user "fileMaster"
  user:
    name: fileMaster
    shell: /bin/bash
    groups: fileShareGroup,davfs2
    uid: 1002
  become: yes

- name: add user "pi" to groups
  user:
    append: true
    name: pi
    groups: fileShareGroup,davfs2
  become: yes
