
- name: create directory - mountpoint for strato hidrive
  file:
    path: /media/cloud
    state: directory
    mode: '0755'
    owner: fileMaster
  become: yes

- name: create directory - mountpoint for local drive
  file:
    path: /media/data
    state: directory
    mode: '0755'
  become: yes

- name: Mount up device PlatteImSchrank by UUID
  mount:
    name: /media/data
    src: UUID=8f84ffcf-6ae2-491f-99dd-f9c6d409701b
    fstype: ext4
    opts: defaults,nofail,x-systemd.device-timeout=5
    state: mounted
  become: yes

- name: Mount up device strato hidrive
  mount:
    name: /media/cloud
    src: https://webdav.hidrive.strato.com
    fstype: davfs
    opts: noauto,uid=fileMaster,gid=fileShareGroup
    state: present
  become: yes
