---

- name: ansible
  apt:
    name: ansible
    state: latest
  become: yes

#- name: install ansible community general
#  command: "ansible-galaxy collection install community.general"
#  become: yes

- name: build tools
  apt:
    name: autoconf,make
    state: latest
  become: yes

- name: vim editor
  apt:
    name: vim
    state: latest
  become: yes

- name: python
  apt:
    name: python
    state: latest
  become: yes

- name: pip
  apt:
    name: python-pip
    state: latest
  become: yes

- name: pip3
  apt:
    name: python3-pip
    state: latest
  become: yes

- name: fuse
  apt:
    name: fuse
    state: latest
  become: yes

- name: sshfs
  apt:
    name: sshfs
    state: latest
  become: yes

- name: davfs2 - webdav for strato hidrive
  apt:
    name: davfs2
    state: latest
  become: yes

- name: dnsutils - bind and so
  apt:
   name: dnsutils
   state: latest
  become: yes
