---

- name: ansible
  apt:
    name: ansible
    state: latest
  register: installation
  become: yes

- name: build tools
  apt:
    name: autoconf,make
    state: latest
  register: installation
  become: yes

- name: vim editor
  apt:
    name: vim
    state: latest
  register: installation
  become: yes

- name: python
  apt:
    name: python
    state: latest
  register: installation
  become: yes

- name: pip
  apt:
    name: python-pip
    state: latest
  register: installation
  become: yes

- name: pip3
  apt:
    name: python3-pip
    state: latest
  register: installation
  become: yes
