- git:
    repo: 'https://github.com/pi-hole/pi-hole.git'
    dest: ~/Pi-hole
    depth: 1
    update: yes

- name: Execute installation of pi-hole
  become: yes
  shell: bash basic-install.sh
  args:
    chdir: /home/pi/Pi-hole/automated install/
#pihole -up to update
